// Client-Facing Product Spec export to Word (.docx), RTF, and PDF — the non-technical
// companion document (see ClientFacingSpec in productSpecTypes.ts and
// handleGenerateClientSpec in ProductTab.tsx). Reuses the same brand palette and Markdown
// block parser as the technical spec's own exporters (productSpecExport.ts) so the two
// documents look like a matched pair, but with a simpler title page (no grounded-sources
// list or per-section "Drafted by" bylines — a stakeholder reading this doesn't need to
// know which AI agent wrote which paragraph) and no target-tool/tech metadata, since this
// document is deliberately scoped to what the product does and looks like, not how it's built.

import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";
import type { Paragraph as ParagraphT, Table as TableT } from "docx";
import type { ProductSpec } from "./productSpecTypes";
import {
  BRAND,
  hexToRgb01,
  parseMarkdownLiteBlocks,
  splitBoldSegments,
  stripBoldMarkers,
  escapeRtf,
  buildRtfTable,
  wrapText,
  RTF_COLOR_TABLE,
  RTF_CF,
} from "./productSpecExport";

function clientSpecDateLabel(spec: ProductSpec): string {
  const at = spec.clientFacingSpec?.generatedAt || spec.createdAt;
  return new Date(at).toLocaleDateString(undefined, { year: "numeric", month: "long" });
}

// A style-inspiration reference (if the product owner attached one during the technical
// spec's pre-flight — see ProductSpecPreflightQuestion.isStyleInspiration) is genuinely
// client-relevant ("here's the look we designed toward"), unlike the rest of pre-flight
// Q&A, which is either implementation detail or already folded into the sections below.
function styleInspirationLine(spec: ProductSpec): string | null {
  const qa = (spec.preflightQuestions || []).find(q => q.isStyleInspiration && q.answer);
  return qa?.answer && !/^no style inspiration/i.test(qa.answer) ? qa.answer : null;
}

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

export async function buildClientFacingSpecDocx(spec: ProductSpec): Promise<Blob> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, Header, Footer, PageNumber, PageBreak,
    Table, TableRow, TableCell, WidthType, ShadingType, BorderStyle,
  } = await import("docx");

  const PAGE_W = 12240;
  const PAGE_H = 15840;
  const MARGIN = 1080;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  const dateLabel = clientSpecDateLabel(spec);
  const styleLine = styleInspirationLine(spec);
  const noBorder = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };

  const header = new Header({
    children: [
      new Table({
        width: { size: CONTENT_W, type: WidthType.DXA },
        columnWidths: [CONTENT_W / 2, CONTENT_W / 2],
        borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder, insideHorizontal: noBorder, insideVertical: noBorder },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                width: { size: CONTENT_W / 2, type: WidthType.DXA },
                borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder },
                children: [new Paragraph({ children: [new TextRun({ text: `${spec.title} — Client-Facing Product Spec`, font: "Arial", bold: true, color: BRAND.blue, size: 18 })] })],
              }),
              new TableCell({
                width: { size: CONTENT_W / 2, type: WidthType.DXA },
                borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder },
                children: [new Paragraph({ alignment: "right", children: [new TextRun({ text: "DRAFT — FOR CLIENT REVIEW", font: "Arial", color: BRAND.muted, size: 16 })] })],
              }),
            ],
          }),
        ],
      }),
      new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.blue, size: 6, space: 1 } }, spacing: { after: 80, before: 0 } }),
    ],
  });

  const footer = new Footer({
    children: [
      new Paragraph({
        border: { top: { style: BorderStyle.SINGLE, color: BRAND.ruleLight, size: 4, space: 1 } },
        tabStops: [{ type: "right", position: CONTENT_W - 60 }],
        spacing: { before: 80, after: 0 },
        children: [
          new TextRun({ text: `Generated by Orchestra — ${dateLabel}`, font: "Arial", color: BRAND.muted, size: 16 }),
          new TextRun({ text: "\tPage ", font: "Arial", color: BRAND.muted, size: 16 }),
          new TextRun({ children: [PageNumber.CURRENT], font: "Arial", color: BRAND.muted, size: 16 }),
        ],
      }),
    ],
  });

  const children: (ParagraphT | TableT)[] = [];

  // --- Title page ---------------------------------------------------------
  children.push(
    new Paragraph({ spacing: { before: 1440, after: 0 }, children: [new TextRun({ text: "CLIENT-FACING PRODUCT SPECIFICATION", font: "Arial", bold: true, color: BRAND.blue, size: 20, characterSpacing: 120 })] }),
    new Paragraph({ spacing: { before: 60, after: 80 }, children: [new TextRun({ text: spec.title, font: "Arial", bold: true, color: BRAND.navy, size: 72 })] })
  );
  if (spec.subtitle) {
    children.push(new Paragraph({ spacing: { before: 0, after: 60 }, children: [new TextRun({ text: spec.subtitle, font: "Arial", color: BRAND.blue, size: 36 })] }));
  }
  children.push(
    new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.accent, size: 16, space: 1 } }, spacing: { before: 200, after: 0 } }),
    new Paragraph({ spacing: { before: 400, after: 80 }, children: [new TextRun({ text: "Document Purpose", font: "Arial", bold: true, color: BRAND.navy, size: 24 })] }),
    new Paragraph({
      spacing: { before: 60, after: 100 },
      children: [new TextRun({ text: `This document describes what ${spec.title} will do, why it's being built, and how it behaves and looks from a user's point of view — for stakeholder review, not for engineering handoff. ${spec.appConcept || ""}`, font: "Arial", color: BRAND.gray, size: 22 })],
    })
  );
  if (styleLine) {
    children.push(
      new Paragraph({ spacing: { before: 240, after: 60 }, children: [new TextRun({ text: "Style Inspiration", font: "Arial", bold: true, color: BRAND.navy, size: 20 })] }),
      new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: styleLine, font: "Arial", color: BRAND.gray, size: 18 })] })
    );
  }
  children.push(
    new Paragraph({
      spacing: { before: 480, after: 80 },
      children: [
        new TextRun({ text: "Prepared:  ", font: "Arial", bold: true, color: BRAND.gray, size: 20 }),
        new TextRun({ text: dateLabel, font: "Arial", color: BRAND.gray, size: 20 }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // --- Section content -----------------------------------------------------
  const buildTable = (rows: string[][]) => {
    const [headerRow, ...bodyRows] = rows;
    const colCount = headerRow.length;
    const baseWidth = Math.floor(CONTENT_W / colCount);
    const colWidths = Array(colCount).fill(baseWidth);
    colWidths[colCount - 1] += CONTENT_W - baseWidth * colCount;

    const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: BRAND.tableBorder };
    const cellBorders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };
    const cellMargins = { top: 100, bottom: 100, left: 120, right: 120 };

    const makeCell = (text: string, width: number, opts: { header?: boolean; firstCol?: boolean }) =>
      new TableCell({
        width: { size: width, type: WidthType.DXA },
        borders: cellBorders,
        margins: cellMargins,
        shading: opts.header
          ? { fill: BRAND.navy, type: ShadingType.CLEAR, color: "auto" }
          : opts.firstCol
          ? { fill: BRAND.labelFill, type: ShadingType.CLEAR, color: "auto" }
          : undefined,
        children: [new Paragraph({ children: [new TextRun({ text: stripBoldMarkers(text), font: "Arial", bold: !!(opts.header || opts.firstCol), color: opts.header ? "FFFFFF" : opts.firstCol ? BRAND.navy : BRAND.gray, size: 20 })] })],
      });

    return new Table({
      width: { size: CONTENT_W, type: WidthType.DXA },
      columnWidths: colWidths,
      rows: [
        new TableRow({ tableHeader: true, children: headerRow.map((cell, ci) => makeCell(cell, colWidths[ci], { header: true })) }),
        ...bodyRows.map(r => new TableRow({ children: r.map((cell, ci) => makeCell(cell, colWidths[ci], { firstCol: ci === 0 })) })),
      ],
    });
  };

  for (const section of spec.clientFacingSpec?.sections || []) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 200 }, children: [new TextRun({ text: section.heading, font: "Arial", bold: true, color: BRAND.navy, size: 36 })] }));
    children.push(new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.blue, size: 12, space: 1 } }, spacing: { after: 200, before: 0 } }));

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "h2") {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 80 }, children: [new TextRun({ text: block.text, font: "Arial", bold: true, color: BRAND.blue, size: 28 })] }));
      } else if (block.type === "h3") {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 60 }, children: [new TextRun({ text: block.text, font: "Arial", bold: true, color: BRAND.gray, size: 24 })] }));
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) {
          children.push(new Paragraph({ children: [new TextRun({ text: codeLine || " ", font: "Consolas", size: 18, color: BRAND.gray })], spacing: { after: 0 } }));
        }
      } else if (block.type === "table") {
        children.push(buildTable(block.rows));
        children.push(new Paragraph({ spacing: { after: 200 } }));
      } else if (block.type === "bullet" || block.type === "numbered") {
        children.push(
          new Paragraph({
            children: splitBoldSegments(block.text).map(seg => new TextRun({ text: seg.text, bold: seg.bold, font: "Arial", size: 22, color: seg.bold ? BRAND.navy : BRAND.gray })),
            bullet: { level: 0 },
            spacing: { after: 40, before: 40 },
          })
        );
      } else {
        children.push(
          new Paragraph({
            children: splitBoldSegments(block.text).map(seg => new TextRun({ text: seg.text, bold: seg.bold, font: "Arial", size: 22, color: seg.bold ? BRAND.navy : BRAND.gray })),
            spacing: { after: 100, before: 60 },
          })
        );
      }
    }
  }

  children.push(
    new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.ruleLight, size: 4, space: 1 } }, spacing: { before: 160, after: 160 } }),
    new Paragraph({ alignment: "center", spacing: { before: 240, after: 80 }, children: [new TextRun({ text: "— End of Document —", font: "Arial", italics: true, color: BRAND.muted, size: 20 })] }),
    new Paragraph({ alignment: "center", children: [new TextRun({ text: `${spec.title} Client-Facing Product Spec  |  ${dateLabel}  |  AI-Generated Draft`, font: "Arial", color: BRAND.faint, size: 18 })] })
  );

  const doc = new Document({
    sections: [
      {
        properties: { page: { size: { width: PAGE_W, height: PAGE_H }, margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN, header: 708, footer: 708 } } },
        headers: { default: header },
        footers: { default: footer },
        children,
      },
    ],
  });
  return Packer.toBlob(doc);
}

// ---------------------------------------------------------------------------
// RTF
// ---------------------------------------------------------------------------

export function buildClientFacingSpecRtf(spec: ProductSpec): string {
  const dateLabel = clientSpecDateLabel(spec);
  const styleLine = styleInspirationLine(spec);
  const lines: string[] = [];

  lines.push(
    `{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}{\\f1 Consolas;}}{\\colortbl;${RTF_COLOR_TABLE.map(cHex => `\\red${parseInt(cHex.slice(0, 2), 16)}\\green${parseInt(cHex.slice(2, 4), 16)}\\blue${parseInt(cHex.slice(4, 6), 16)};`).join("")}}`
  );
  lines.push(
    `{\\header\\pard\\tqr\\tx9360\\fs18\\b\\cf${RTF_CF.blue} ${escapeRtf(`${spec.title} — Client-Facing Product Spec`)}\\b0\\tab\\fs16\\cf${RTF_CF.muted} ${escapeRtf("DRAFT — FOR CLIENT REVIEW")}\\par}`,
    `{\\footer\\pard\\tqr\\tx9360\\fs16\\cf${RTF_CF.muted} ${escapeRtf(`Generated by Orchestra — ${dateLabel}`)}\\tab Page \\chpgn\\par}`
  );

  lines.push(`\\f0\\fs20\\b\\cf${RTF_CF.blue}\\expndtw60 CLIENT-FACING PRODUCT SPECIFICATION\\expndtw0\\b0\\par`);
  lines.push(`\\fs72\\b\\cf${RTF_CF.navy} ${escapeRtf(spec.title)}\\b0\\par`);
  if (spec.subtitle) lines.push(`\\fs36\\cf${RTF_CF.blue} ${escapeRtf(spec.subtitle)}\\par`);
  lines.push(`\\brdrb\\brdrs\\brdrw20\\brdrcf${RTF_CF.accent}\\par\\pard\\par`);
  lines.push(`\\fs24\\b\\cf${RTF_CF.navy} Document Purpose\\b0\\par`);
  lines.push(
    `\\fs22\\cf${RTF_CF.gray} This document describes what ${escapeRtf(spec.title)} will do, why it's being built, and how it behaves and looks from a user's point of view — for stakeholder review, not for engineering handoff. ${escapeRtf(spec.appConcept || "")}\\par\\par`
  );
  if (styleLine) {
    lines.push(`\\fs20\\b\\cf${RTF_CF.navy} Style Inspiration\\b0\\par`);
    lines.push(`\\fs18\\cf${RTF_CF.gray} ${escapeRtf(styleLine)}\\par\\par`);
  }
  lines.push(`\\fs20\\cf${RTF_CF.gray}\\b Prepared:\\b0  ${escapeRtf(dateLabel)}\\par`);
  lines.push("\\page");

  for (const section of spec.clientFacingSpec?.sections || []) {
    lines.push(`\\fs36\\b\\cf${RTF_CF.navy} ${escapeRtf(section.heading)}\\b0\\par`);
    lines.push(`\\brdrb\\brdrs\\brdrw15\\brdrcf${RTF_CF.blue}\\par\\pard\\par`);

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "table") {
        lines.push(buildRtfTable(block.rows));
        continue;
      }
      const plain = escapeRtf(stripBoldMarkers(block.text));
      if (block.type === "h2") {
        lines.push(`\\fs28\\b\\cf${RTF_CF.blue} ${plain}\\b0\\par`);
      } else if (block.type === "h3") {
        lines.push(`\\fs24\\b\\cf${RTF_CF.gray} ${plain}\\b0\\par`);
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) lines.push(`\\f1\\fs18\\cf${RTF_CF.gray} ${escapeRtf(codeLine || " ")}\\f0\\par`);
      } else if (block.type === "bullet" || block.type === "numbered") {
        lines.push(`\\fs22\\cf${RTF_CF.gray} \\bullet \\tab ${plain}\\par`);
      } else {
        lines.push(`\\fs22\\cf${RTF_CF.gray} ${plain}\\par`);
      }
    }
    lines.push("\\par");
  }

  lines.push(`\\brdrb\\brdrs\\brdrw10\\brdrcf${RTF_CF.ruleLight}\\par\\pard\\par`);
  lines.push(`\\qc\\fs20\\i\\cf${RTF_CF.muted} ${escapeRtf("— End of Document —")}\\i0\\par`);
  lines.push(`\\qc\\fs18\\cf${RTF_CF.faint} ${escapeRtf(spec.title)} Client-Facing Product Spec  |  ${escapeRtf(dateLabel)}  |  AI-Generated Draft\\par`);
  lines.push("}");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 54;
const HEADER_H = 34;
const FOOTER_H = 28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const CONTENT_TOP = PAGE_HEIGHT - MARGIN - HEADER_H;
const CONTENT_BOTTOM = MARGIN + FOOTER_H;

export async function buildClientFacingSpecPdf(spec: ProductSpec): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const regularFont = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const italicFont = await doc.embedFont(StandardFonts.HelveticaOblique);
  const monoFont = await doc.embedFont(StandardFonts.Courier);

  const [navy, blue, gray, muted, faint, accent, tableBorder, ruleLight, labelFill] = [
    BRAND.navy, BRAND.blue, BRAND.gray, BRAND.muted, BRAND.faint, BRAND.accent, BRAND.tableBorder, BRAND.ruleLight, BRAND.labelFill,
  ].map(hexToRgb01);
  const c = (rgbTuple: [number, number, number]) => rgb(...rgbTuple);

  const dateLabel = clientSpecDateLabel(spec);
  const styleLine = styleInspirationLine(spec);
  const allPages: PDFPage[] = [];

  const drawHeaderChrome = (p: PDFPage) => {
    const y = PAGE_HEIGHT - MARGIN;
    p.drawText(`${spec.title} — Client-Facing Product Spec`, { x: MARGIN, y: y - 9, size: 9, font: boldFont, color: c(blue) });
    const rightText = "DRAFT — FOR CLIENT REVIEW";
    const rightWidth = regularFont.widthOfTextAtSize(rightText, 8);
    p.drawText(rightText, { x: PAGE_WIDTH - MARGIN - rightWidth, y: y - 8, size: 8, font: regularFont, color: c(muted) });
    p.drawLine({ start: { x: MARGIN, y: y - 16 }, end: { x: PAGE_WIDTH - MARGIN, y: y - 16 }, thickness: 0.75, color: c(blue) });
  };

  let page: PDFPage = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  allPages.push(page);
  drawHeaderChrome(page);
  let cursorY = CONTENT_TOP;

  const ensureSpace = (neededHeight: number) => {
    if (cursorY - neededHeight < CONTENT_BOTTOM) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      allPages.push(page);
      drawHeaderChrome(page);
      cursorY = CONTENT_TOP;
    }
  };

  const drawParagraph = (text: string, font: PDFFont, fontSize: number, opts: { color?: [number, number, number]; indent?: number; lineHeight?: number; align?: "left" | "center" } = {}) => {
    const indent = opts.indent || 0;
    const lineHeight = opts.lineHeight || fontSize * 1.4;
    const color = c(opts.color || gray);
    const lines = wrapText(text, font, fontSize, CONTENT_WIDTH - indent);
    for (const line of lines) {
      ensureSpace(lineHeight);
      const x = opts.align === "center" ? MARGIN + (CONTENT_WIDTH - font.widthOfTextAtSize(line, fontSize)) / 2 : MARGIN + indent;
      page.drawText(line, { x, y: cursorY - fontSize, size: fontSize, font, color });
      cursorY -= lineHeight;
    }
  };

  const drawRule = (color: [number, number, number], thickness: number, gapBefore = 8, gapAfter = 8) => {
    cursorY -= gapBefore;
    ensureSpace(thickness);
    page.drawLine({ start: { x: MARGIN, y: cursorY }, end: { x: PAGE_WIDTH - MARGIN, y: cursorY }, thickness, color: c(color) });
    cursorY -= gapAfter;
  };

  const drawTable = (rows: string[][]) => {
    const [headerRow, ...bodyRows] = rows;
    const colCount = headerRow.length;
    const colWidth = CONTENT_WIDTH / colCount;
    const cellPad = 5;
    const fontSize = 9;
    const lineHeight = fontSize * 1.3;

    const drawRowLine = (cells: string[], isHeader: boolean) => {
      const wrapped = cells.map(cell => wrapText(stripBoldMarkers(cell), isHeader ? boldFont : regularFont, fontSize, colWidth - cellPad * 2));
      const rowHeight = Math.max(...wrapped.map(w => w.length), 1) * lineHeight + cellPad * 2;
      ensureSpace(rowHeight);
      const rowTop = cursorY;
      for (let ci = 0; ci < colCount; ci++) {
        const cellX = MARGIN + ci * colWidth;
        if (isHeader) {
          page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, color: c(navy) });
        } else if (ci === 0) {
          page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, color: c(labelFill) });
        }
        page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, borderColor: c(tableBorder), borderWidth: 0.5, opacity: 0 });
        const textColor = isHeader ? rgb(1, 1, 1) : ci === 0 ? c(navy) : c(gray);
        wrapped[ci].forEach((line, li) => {
          page.drawText(line, { x: cellX + cellPad, y: rowTop - cellPad - fontSize - li * lineHeight, size: fontSize, font: isHeader || ci === 0 ? boldFont : regularFont, color: textColor });
        });
      }
      cursorY = rowTop - rowHeight;
    };

    drawRowLine(headerRow, true);
    for (const row of bodyRows) drawRowLine(row, false);
    cursorY -= 10;
  };

  // --- Title page ---
  const titlePageStartCount = allPages.length;
  cursorY -= 20;
  drawParagraph("CLIENT-FACING PRODUCT SPECIFICATION", boldFont, 10, { color: blue });
  cursorY -= 6;
  drawParagraph(spec.title, boldFont, 30, { color: navy });
  if (spec.subtitle) drawParagraph(spec.subtitle, regularFont, 15, { color: blue });
  drawRule(accent, 1.5, 10, 16);
  drawParagraph("Document Purpose", boldFont, 12, { color: navy });
  cursorY -= 2;
  drawParagraph(
    `This document describes what ${spec.title} will do, why it's being built, and how it behaves and looks from a user's point of view — for stakeholder review, not for engineering handoff. ${spec.appConcept || ""}`,
    regularFont,
    10.5,
    { color: gray }
  );
  if (styleLine) {
    cursorY -= 14;
    drawParagraph("Style Inspiration", boldFont, 11, { color: navy });
    cursorY -= 2;
    drawParagraph(styleLine, regularFont, 9.5, { color: gray });
  }
  cursorY -= 16;
  drawParagraph(`Prepared:  ${dateLabel}`, regularFont, 9.5, { color: gray });

  if (allPages.length === titlePageStartCount) {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    allPages.push(page);
    drawHeaderChrome(page);
  }
  cursorY = CONTENT_TOP;

  // --- Sections ---
  for (const section of spec.clientFacingSpec?.sections || []) {
    ensureSpace(50);
    drawParagraph(section.heading, boldFont, 16, { color: navy });
    drawRule(blue, 1.2, 4, 10);

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "table") {
        drawTable(block.rows);
        cursorY -= 4;
        continue;
      }
      const plain = stripBoldMarkers(block.text);
      if (block.type === "h2") {
        cursorY -= 4;
        drawParagraph(plain, boldFont, 12.5, { color: blue });
      } else if (block.type === "h3") {
        drawParagraph(plain, boldFont, 11, { color: gray });
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) drawParagraph(codeLine || " ", monoFont, 8.5, { color: gray, indent: 12, lineHeight: 11 });
      } else if (block.type === "bullet" || block.type === "numbered") {
        drawParagraph(`•  ${plain}`, regularFont, 10, { indent: 10 });
      } else {
        drawParagraph(plain, regularFont, 10);
      }
      cursorY -= 4;
    }
    cursorY -= 10;
  }

  // --- Closing block ---
  drawRule(ruleLight, 0.75, 8, 16);
  drawParagraph("— End of Document —", italicFont, 10, { color: muted, align: "center" });
  drawParagraph(`${spec.title} Client-Facing Product Spec  |  ${dateLabel}  |  AI-Generated Draft`, regularFont, 9, { color: faint, align: "center" });

  allPages.forEach((p, idx) => {
    const y = MARGIN + FOOTER_H - 14;
    p.drawLine({ start: { x: MARGIN, y: y + 10 }, end: { x: PAGE_WIDTH - MARGIN, y: y + 10 }, thickness: 0.5, color: c(ruleLight) });
    p.drawText(`Generated by Orchestra — ${dateLabel}`, { x: MARGIN, y, size: 8, font: regularFont, color: c(muted) });
    const pageText = `Page ${idx + 1}`;
    const pageTextWidth = regularFont.widthOfTextAtSize(pageText, 8);
    p.drawText(pageText, { x: PAGE_WIDTH - MARGIN - pageTextWidth, y, size: 8, font: regularFont, color: c(muted) });
  });

  return doc.save();
}
