// Product spec export to Word (.docx), RTF, and PDF. All three formats share one
// lightweight Markdown parser (parseMarkdownLiteBlocks) and one brand style (BRAND below)
// so headings/bullets/tables/the title page render consistently across formats instead of
// three independently-drifting implementations.
//
// The visual style here (colors, type sizes, header/footer layout, title page structure)
// was reverse-engineered from a reference document the user provided (a Trimble/SketchUp
// product spec) — see BRAND for the exact palette and the title-page/header/footer builders
// below for the layout. Business-specific wording in that reference ("CONFIDENTIAL — FOR
// INTERNAL USE", a real company name, a fixed "v1.0") was deliberately NOT copied verbatim —
// this tool generates drafts for arbitrary projects, so those became generic equivalents
// ("AI-GENERATED — DRAFT", "Generated by Orchestra") rather than false claims.
//
// KNOWN LIMITATION: this is a "lite" Markdown parser, not a full CommonMark implementation.
// It handles what the drafting agents actually produce (headings, bullets, numbered lists,
// fenced code blocks, pipe tables, **bold** spans, plain paragraphs) but does NOT handle
// nested/multi-level lists (everything renders at a single indent level) or table cell
// alignment markers (:---:) beyond stripping them.

import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";
import type { Paragraph as ParagraphT, Table as TableT } from "docx";
import type { ProductSpec } from "./productSpecTypes";
import { VIBE_CODING_TOOLS } from "./productSpecTypes";

// ---------------------------------------------------------------------------
// Shared brand style — one source of truth for all three renderers
// ---------------------------------------------------------------------------

export const BRAND = {
  navy: "003865", // headings, title, table header fill, bold inline lead-ins
  blue: "0063A3", // subtitle, H2, header brand text, rule under H1
  gray: "464B52", // body text, H3
  muted: "999999", // header/footer chrome, captions
  faint: "BBBBBB", // end-of-document fine print
  accent: "FBAD26", // title page divider
  tableBorder: "CCCCCC",
  ruleLight: "E0E1E2", // footer rule
  labelFill: "EAF2FA", // table first-column fill
};

export function hexToRgb01(hex: string): [number, number, number] {
  const n = parseInt(hex, 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

function specDateLabel(spec: ProductSpec): string {
  return new Date(spec.createdAt).toLocaleDateString(undefined, { year: "numeric", month: "long" });
}

function specToolLabel(spec: ProductSpec): string {
  return VIBE_CODING_TOOLS.find(t => t.id === spec.targetTool)?.label || spec.targetTool;
}

function specTypeLabel(spec: ProductSpec): string {
  return spec.projectType === "update" ? "Update to Existing App" : "New Application";
}

function sourceTypeLabel(sourceType: string): string {
  if (sourceType === "github") return "GitHub Repository";
  if (sourceType === "codebase_zip") return "Codebase Archive (.zip)";
  if (sourceType === "website" || sourceType === "web") return "Website";
  if (sourceType === "youtube") return "YouTube";
  if (sourceType === "google_drive") return "Google Drive";
  if (sourceType === "text") return "Pasted Text";
  return "File";
}

// Cap on the title page's "Knowledge Sources Referenced" list — a huge knowledge base
// would otherwise make the title page itself unreasonably long; the cap keeps it a useful
// at-a-glance summary rather than a full re-listing of every attached source.
const MAX_GROUNDED_SOURCES_SHOWN = 12;

// ---------------------------------------------------------------------------
// Shared lightweight Markdown block parser
// ---------------------------------------------------------------------------

export type MarkdownBlock =
  | { type: "h2" | "h3"; text: string }
  | { type: "bullet" | "numbered"; text: string }
  | { type: "code"; text: string }
  | { type: "table"; rows: string[][] }
  | { type: "paragraph"; text: string };

function isTableRow(line: string): boolean {
  return /^\s*\|.*\|\s*$/.test(line);
}

function isTableSeparatorRow(line: string): boolean {
  return /^\s*\|?[\s:|-]+\|?\s*$/.test(line) && line.includes("-");
}

function parseTableRowCells(line: string): string[] {
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map(c => c.trim());
}

export function parseMarkdownLiteBlocks(content: string): MarkdownBlock[] {
  const blocks: MarkdownBlock[] = [];
  const lines = content.split("\n");
  let inCode = false;
  let codeBuffer: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const rawLine = lines[i];
    const line = rawLine.trimEnd();
    if (line.trim().startsWith("```")) {
      if (inCode) {
        blocks.push({ type: "code", text: codeBuffer.join("\n") });
        codeBuffer = [];
        inCode = false;
      } else {
        inCode = true;
      }
      i++;
      continue;
    }
    if (inCode) {
      codeBuffer.push(rawLine);
      i++;
      continue;
    }
    const trimmed = line.trim();
    if (!trimmed) {
      i++;
      continue;
    }

    // A pipe-table: a `| a | b |` row immediately followed by a `|---|---|` separator row.
    // Requiring both lines (not just "contains a pipe") keeps a stray "a | b" sentence from
    // being misread as a table.
    if (isTableRow(trimmed) && i + 1 < lines.length && isTableSeparatorRow(lines[i + 1].trim())) {
      const rows: string[][] = [parseTableRowCells(trimmed)];
      i += 2; // header row + separator row
      while (i < lines.length && isTableRow(lines[i].trim())) {
        rows.push(parseTableRowCells(lines[i].trim()));
        i++;
      }
      blocks.push({ type: "table", rows });
      continue;
    }

    if (/^###\s+/.test(trimmed)) {
      blocks.push({ type: "h3", text: trimmed.replace(/^###\s+/, "") });
    } else if (/^##\s+/.test(trimmed)) {
      blocks.push({ type: "h2", text: trimmed.replace(/^##\s+/, "") });
    } else if (/^#\s+/.test(trimmed)) {
      blocks.push({ type: "h2", text: trimmed.replace(/^#\s+/, "") });
    } else if (/^[-*]\s+/.test(trimmed)) {
      blocks.push({ type: "bullet", text: trimmed.replace(/^[-*]\s+/, "") });
    } else if (/^\d+[.)]\s+/.test(trimmed)) {
      blocks.push({ type: "numbered", text: trimmed.replace(/^\d+[.)]\s+/, "") });
    } else {
      blocks.push({ type: "paragraph", text: trimmed });
    }
    i++;
  }
  // An unterminated fenced block (agent forgot the closing ```) — flush what we have
  // rather than silently dropping it.
  if (inCode && codeBuffer.length > 0) {
    blocks.push({ type: "code", text: codeBuffer.join("\n") });
  }
  return blocks;
}

/** Splits "some **bold** text" into plain/bold segments for renderers that support
 *  inline run-level formatting (DOCX and PDF; RTF uses the plain-text fallback below). */
export function splitBoldSegments(text: string): { text: string; bold: boolean }[] {
  const segments: { text: string; bold: boolean }[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text))) {
    if (match.index > lastIndex) segments.push({ text: text.slice(lastIndex, match.index), bold: false });
    segments.push({ text: match[1], bold: true });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) segments.push({ text: text.slice(lastIndex), bold: false });
  return segments.length > 0 ? segments : [{ text, bold: false }];
}

/** For renderers with no inline formatting (RTF's plain-text fallback) — just drop the **
 *  markers rather than printing them literally. */
export function stripBoldMarkers(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1");
}

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

export async function buildProductSpecDocx(spec: ProductSpec): Promise<Blob> {
  // Dynamic import: `docx` is a sizeable dependency and most sessions never touch export,
  // so it's kept out of the main bundle and only fetched when this function actually runs
  // (mirrors the existing pattern in src/lib/officeFiles.ts).
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, Header, Footer, PageNumber, PageBreak,
    Table, TableRow, TableCell, WidthType, ShadingType, BorderStyle,
  } = await import("docx");

  // US Letter in twips (DXA) — docx defaults to A4, so this must be set explicitly.
  const PAGE_W = 12240;
  const PAGE_H = 15840;
  const MARGIN = 1080; // 0.75in, matching the reference document
  const CONTENT_W = PAGE_W - MARGIN * 2; // 10080

  const dateLabel = specDateLabel(spec);
  const toolLabel = specToolLabel(spec);
  const typeLabel = specTypeLabel(spec);
  const noBorder = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };

  // --- Running header: two-column borderless table (brand text left, status right), plus
  // a separate paragraph with a bottom rule — mirrors the reference doc's own technique.
  const header = new Header({
    children: [
      new Table({
        width: { size: CONTENT_W, type: WidthType.DXA },
        columnWidths: [CONTENT_W / 2, CONTENT_W / 2],
        borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder, insideHorizontal: noBorder, insideVertical: noBorder },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                width: { size: CONTENT_W / 2, type: WidthType.DXA },
                borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder },
                children: [new Paragraph({ children: [new TextRun({ text: `${spec.title} — Product Specification`, font: "Arial", bold: true, color: BRAND.blue, size: 18 })] })],
              }),
              new TableCell({
                width: { size: CONTENT_W / 2, type: WidthType.DXA },
                borders: { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder },
                children: [
                  new Paragraph({
                    alignment: "right",
                    children: [new TextRun({ text: "AI-GENERATED — DRAFT", font: "Arial", color: BRAND.muted, size: 16 })],
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
      new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.blue, size: 6, space: 1 } },
        spacing: { after: 80, before: 0 },
      }),
    ],
  });

  // --- Running footer: single line, rule above, brand text left / page number right.
  const footer = new Footer({
    children: [
      new Paragraph({
        border: { top: { style: BorderStyle.SINGLE, color: BRAND.ruleLight, size: 4, space: 1 } },
        tabStops: [{ type: "right", position: CONTENT_W - 60 }],
        spacing: { before: 80, after: 0 },
        children: [
          new TextRun({ text: `Generated by Orchestra — ${dateLabel}`, font: "Arial", color: BRAND.muted, size: 16 }),
          new TextRun({ text: "\tPage ", font: "Arial", color: BRAND.muted, size: 16 }),
          new TextRun({ children: [PageNumber.CURRENT], font: "Arial", color: BRAND.muted, size: 16 }),
        ],
      }),
    ],
  });

  const children: (ParagraphT | TableT)[] = [];

  // --- Title page ---------------------------------------------------------
  children.push(
    new Paragraph({
      spacing: { before: 1440, after: 0 },
      children: [new TextRun({ text: "PRODUCT SPECIFICATION", font: "Arial", bold: true, color: BRAND.blue, size: 20, characterSpacing: 120 })],
    }),
    new Paragraph({
      spacing: { before: 60, after: 80 },
      children: [new TextRun({ text: spec.title, font: "Arial", bold: true, color: BRAND.navy, size: 72 })],
    })
  );
  if (spec.subtitle) {
    children.push(
      new Paragraph({
        spacing: { before: 0, after: 60 },
        children: [new TextRun({ text: spec.subtitle, font: "Arial", color: BRAND.blue, size: 36 })],
      })
    );
  }
  children.push(
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.accent, size: 16, space: 1 } },
      spacing: { before: 200, after: 0 },
    }),
    new Paragraph({
      spacing: { before: 400, after: 80 },
      children: [new TextRun({ text: "Document Purpose", font: "Arial", bold: true, color: BRAND.navy, size: 24 })],
    }),
    new Paragraph({
      spacing: { before: 60, after: 100 },
      children: [
        new TextRun({
          text: `This document is a comprehensive, implementation-ready product specification for ${spec.title}, produced collaboratively by a multi-agent AI product team. ${spec.appConcept || ""}`,
          font: "Arial",
          color: BRAND.gray,
          size: 22,
        }),
      ],
    })
  );

  if (spec.groundedSources && spec.groundedSources.length > 0) {
    children.push(
      new Paragraph({
        spacing: { before: 240, after: 60 },
        children: [new TextRun({ text: "Knowledge Sources Referenced", font: "Arial", bold: true, color: BRAND.navy, size: 20 })],
      })
    );
    for (const src of spec.groundedSources.slice(0, MAX_GROUNDED_SOURCES_SHOWN)) {
      const nameRuns = [new TextRun({ text: `${sourceTypeLabel(src.sourceType)}: `, font: "Arial", bold: true, color: BRAND.gray, size: 18 }), new TextRun({ text: src.name, font: "Arial", color: BRAND.gray, size: 18 })];
      if (src.url) nameRuns.push(new TextRun({ text: `  —  ${src.url}`, font: "Arial", color: BRAND.blue, size: 16 }));
      children.push(new Paragraph({ spacing: { after: 20 }, children: nameRuns }));
      children.push(new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: src.excerpt, font: "Arial", italics: true, color: BRAND.muted, size: 16 })] }));
    }
    if (spec.groundedSources.length > MAX_GROUNDED_SOURCES_SHOWN) {
      children.push(
        new Paragraph({
          spacing: { after: 100 },
          children: [new TextRun({ text: `...and ${spec.groundedSources.length - MAX_GROUNDED_SOURCES_SHOWN} more source(s) not shown here.`, font: "Arial", italics: true, color: BRAND.muted, size: 16 })],
        })
      );
    }
  }

  const metaRuns: InstanceType<typeof TextRun>[] = [
    new TextRun({ text: "Generated:  ", font: "Arial", bold: true, color: BRAND.gray, size: 20 }),
    new TextRun({ text: `${dateLabel}   `, font: "Arial", color: BRAND.gray, size: 20 }),
    new TextRun({ text: "  Target Tool:  ", font: "Arial", bold: true, color: BRAND.gray, size: 20 }),
    new TextRun({ text: `${toolLabel}   `, font: "Arial", color: BRAND.gray, size: 20 }),
    new TextRun({ text: "  Type:  ", font: "Arial", bold: true, color: BRAND.gray, size: 20 }),
    new TextRun({ text: typeLabel, font: "Arial", color: BRAND.gray, size: 20 }),
  ];
  if (spec.projectType === "update" && spec.groundedOnExistingCodebase) {
    metaRuns.push(
      new TextRun({ text: "   Grounded On:  ", font: "Arial", bold: true, color: BRAND.gray, size: 20 }),
      new TextRun({ text: spec.groundedOnExistingCodebase, font: "Arial", color: BRAND.gray, size: 20 })
    );
  }
  children.push(new Paragraph({ spacing: { before: 480, after: 80 }, children: metaRuns }));
  children.push(new Paragraph({ children: [new PageBreak()] }));

  // --- Section content -----------------------------------------------------
  const buildTable = (rows: string[][]) => {
    const [headerRow, ...bodyRows] = rows;
    const colCount = headerRow.length;
    const baseWidth = Math.floor(CONTENT_W / colCount);
    const colWidths = Array(colCount).fill(baseWidth);
    colWidths[colCount - 1] += CONTENT_W - baseWidth * colCount; // remainder to last column, so widths sum exactly

    const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: BRAND.tableBorder };
    const cellBorders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };
    const cellMargins = { top: 100, bottom: 100, left: 120, right: 120 };

    const makeCell = (text: string, width: number, opts: { header?: boolean; firstCol?: boolean }) =>
      new TableCell({
        width: { size: width, type: WidthType.DXA },
        borders: cellBorders,
        margins: cellMargins,
        shading: opts.header
          ? { fill: BRAND.navy, type: ShadingType.CLEAR, color: "auto" }
          : opts.firstCol
          ? { fill: BRAND.labelFill, type: ShadingType.CLEAR, color: "auto" }
          : undefined,
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: stripBoldMarkers(text),
                font: "Arial",
                bold: !!(opts.header || opts.firstCol),
                color: opts.header ? "FFFFFF" : opts.firstCol ? BRAND.navy : BRAND.gray,
                size: 20,
              }),
            ],
          }),
        ],
      });

    return new Table({
      width: { size: CONTENT_W, type: WidthType.DXA },
      columnWidths: colWidths,
      rows: [
        new TableRow({ tableHeader: true, children: headerRow.map((cell, ci) => makeCell(cell, colWidths[ci], { header: true })) }),
        ...bodyRows.map(
          r => new TableRow({ children: r.map((cell, ci) => makeCell(cell, colWidths[ci], { firstCol: ci === 0 })) })
        ),
      ],
    });
  };

  for (const section of spec.sections) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 120 }, children: [new TextRun({ text: section.heading, font: "Arial", bold: true, color: BRAND.navy, size: 36 })] }));
    children.push(new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.blue, size: 12, space: 1 } }, spacing: { after: 200, before: 0 } }));
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Drafted by ${section.authorAgentName}${section.reviewedByAgentName ? ` · Reviewed by ${section.reviewedByAgentName}` : ""}`, italics: true, font: "Arial", size: 16, color: BRAND.muted })],
        spacing: { after: 150 },
      })
    );

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "h2") {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 80 }, children: [new TextRun({ text: block.text, font: "Arial", bold: true, color: BRAND.blue, size: 28 })] }));
      } else if (block.type === "h3") {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 60 }, children: [new TextRun({ text: block.text, font: "Arial", bold: true, color: BRAND.gray, size: 24 })] }));
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) {
          children.push(new Paragraph({ children: [new TextRun({ text: codeLine || " ", font: "Consolas", size: 18, color: BRAND.gray })], spacing: { after: 0 } }));
        }
      } else if (block.type === "table") {
        children.push(buildTable(block.rows));
        children.push(new Paragraph({ spacing: { after: 200 } }));
      } else if (block.type === "bullet" || block.type === "numbered") {
        children.push(
          new Paragraph({
            children: splitBoldSegments(block.text).map(seg => new TextRun({ text: seg.text, bold: seg.bold, font: "Arial", size: 22, color: seg.bold ? BRAND.navy : BRAND.gray })),
            bullet: { level: 0 },
            spacing: { after: 40, before: 40 },
          })
        );
      } else {
        children.push(
          new Paragraph({
            children: splitBoldSegments(block.text).map(seg => new TextRun({ text: seg.text, bold: seg.bold, font: "Arial", size: 22, color: seg.bold ? BRAND.navy : BRAND.gray })),
            spacing: { after: 100, before: 60 },
          })
        );
      }
    }
  }

  // --- Closing block --------------------------------------------------------
  children.push(
    new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, color: BRAND.ruleLight, size: 4, space: 1 } }, spacing: { before: 160, after: 160 } }),
    new Paragraph({
      alignment: "center",
      spacing: { before: 240, after: 80 },
      children: [new TextRun({ text: "— End of Document —", font: "Arial", italics: true, color: BRAND.muted, size: 20 })],
    }),
    new Paragraph({
      alignment: "center",
      children: [new TextRun({ text: `${spec.title} Product Specification  |  ${dateLabel}  |  AI-Generated Draft`, font: "Arial", color: BRAND.faint, size: 18 })],
    })
  );

  const doc = new Document({
    sections: [
      {
        properties: { page: { size: { width: PAGE_W, height: PAGE_H }, margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN, header: 708, footer: 708 } } },
        headers: { default: header },
        footers: { default: footer },
        children,
      },
    ],
  });
  return Packer.toBlob(doc);
}

// ---------------------------------------------------------------------------
// RTF (no external dependency — RTF is a plain-text markup format)
// ---------------------------------------------------------------------------

// Fixed color table index → BRAND color, referenced via \cfN below. Index 0 is left as
// black/auto per RTF convention (readers treat an unset \cf as index 0).
export const RTF_COLOR_TABLE = [BRAND.navy, BRAND.blue, BRAND.gray, BRAND.muted, BRAND.faint, BRAND.accent, BRAND.tableBorder, BRAND.ruleLight];
export const RTF_CF = {
  navy: 1, blue: 2, gray: 3, muted: 4, faint: 5, accent: 6, tableBorder: 7, ruleLight: 8,
};

export function escapeRtf(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    // Non-ASCII characters must be Unicode-escaped in RTF; \uN? with a literal '?' fallback
    // byte keeps older readers from choking on unescaped high characters.
    .split("")
    .map(ch => (ch.charCodeAt(0) > 127 ? `\\u${ch.charCodeAt(0)}?` : ch))
    .join("");
}

/** A real RTF table (bordered grid, header row bold) rather than the old plain-line dump.
 *  Cell shading is deliberately skipped — RTF `\clshdng`/`\clcbpat` support is inconsistent
 *  outside Word, and a bold header row reads clearly without it. Column widths are equal,
 *  matching the DOCX renderer's simplification for arbitrary agent-generated tables. */
export function buildRtfTable(rows: string[][]): string {
  const [headerRow, ...bodyRows] = rows;
  const colCount = headerRow.length;
  const totalTwips = 9360; // matches the RTF page width minus margins used below
  const colWidth = Math.floor(totalTwips / colCount);
  const borders = `\\clbrdrt\\brdrs\\brdrw10\\brdrcf${RTF_CF.tableBorder}\\clbrdrb\\brdrs\\brdrw10\\brdrcf${RTF_CF.tableBorder}\\clbrdrl\\brdrs\\brdrw10\\brdrcf${RTF_CF.tableBorder}\\clbrdrr\\brdrs\\brdrw10\\brdrcf${RTF_CF.tableBorder}`;

  const buildRow = (cells: string[], isHeader: boolean): string => {
    const rowDef = `\\trowd\\trgaph70${cells.map((_, i) => `${borders}\\cellx${(i + 1) * colWidth}`).join("")}`;
    const cellText = cells
      .map(cell => `\\intbl${isHeader ? "\\b" : ""}\\fs20\\cf${RTF_CF.gray} ${escapeRtf(stripBoldMarkers(cell))}${isHeader ? "\\b0" : ""}\\cell`)
      .join("");
    return `${rowDef}${cellText}\\row`;
  };

  return [buildRow(headerRow, true), ...bodyRows.map(r => buildRow(r, false))].join("\n") + "\n\\pard\n";
}

export function buildProductSpecRtf(spec: ProductSpec): string {
  const dateLabel = specDateLabel(spec);
  const lines: string[] = [];

  lines.push(
    `{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}{\\f1 Consolas;}}{\\colortbl;${RTF_COLOR_TABLE.map(cHex => `\\red${parseInt(cHex.slice(0, 2), 16)}\\green${parseInt(cHex.slice(2, 4), 16)}\\blue${parseInt(cHex.slice(4, 6), 16)};`).join("")}}`
  );

  // Running header/footer — supported by Word/LibreOffice; degrades to "no repeating
  // header" in readers that ignore \header/\footer groups, which is a graceful fallback,
  // not a broken document.
  lines.push(
    `{\\header\\pard\\tqr\\tx9360\\fs18\\b\\cf${RTF_CF.blue} ${escapeRtf(`${spec.title} — Product Specification`)}\\b0\\tab\\fs16\\cf${RTF_CF.muted} ${escapeRtf("AI-GENERATED — DRAFT")}\\par}`,
    `{\\footer\\pard\\tqr\\tx9360\\fs16\\cf${RTF_CF.muted} ${escapeRtf(`Generated by Orchestra — ${dateLabel}`)}\\tab Page \\chpgn\\par}`
  );

  // --- Title page ---
  lines.push(`\\f0\\fs20\\b\\cf${RTF_CF.blue}\\expndtw60 PRODUCT SPECIFICATION\\expndtw0\\b0\\par`);
  lines.push(`\\fs72\\b\\cf${RTF_CF.navy} ${escapeRtf(spec.title)}\\b0\\par`);
  if (spec.subtitle) lines.push(`\\fs36\\cf${RTF_CF.blue} ${escapeRtf(spec.subtitle)}\\par`);
  lines.push(`\\brdrb\\brdrs\\brdrw20\\brdrcf${RTF_CF.accent}\\par\\pard\\par`);
  lines.push(`\\fs24\\b\\cf${RTF_CF.navy} Document Purpose\\b0\\par`);
  lines.push(
    `\\fs22\\cf${RTF_CF.gray} This document is a comprehensive, implementation-ready product specification for ${escapeRtf(spec.title)}, produced collaboratively by a multi-agent AI product team. ${escapeRtf(spec.appConcept || "")}\\par\\par`
  );
  if (spec.groundedSources && spec.groundedSources.length > 0) {
    lines.push(`\\fs20\\b\\cf${RTF_CF.navy} Knowledge Sources Referenced\\b0\\par`);
    for (const src of spec.groundedSources.slice(0, MAX_GROUNDED_SOURCES_SHOWN)) {
      let sourceLine = `\\fs18\\cf${RTF_CF.gray}\\b ${escapeRtf(sourceTypeLabel(src.sourceType))}: \\b0 ${escapeRtf(src.name)}`;
      if (src.url) sourceLine += `\\cf${RTF_CF.blue}  —  ${escapeRtf(src.url)}`;
      lines.push(`${sourceLine}\\par`);
      lines.push(`\\fs16\\i\\cf${RTF_CF.muted} ${escapeRtf(src.excerpt)}\\i0\\par\\par`);
    }
    if (spec.groundedSources.length > MAX_GROUNDED_SOURCES_SHOWN) {
      lines.push(`\\fs16\\i\\cf${RTF_CF.muted} ${escapeRtf(`...and ${spec.groundedSources.length - MAX_GROUNDED_SOURCES_SHOWN} more source(s) not shown here.`)}\\i0\\par\\par`);
    }
  }
  const toolLabel = specToolLabel(spec);
  const typeLabel = specTypeLabel(spec);
  let metaLine = `\\fs20\\cf${RTF_CF.gray}\\b Generated:\\b0  ${escapeRtf(dateLabel)}    \\b Target Tool:\\b0  ${escapeRtf(toolLabel)}    \\b Type:\\b0  ${escapeRtf(typeLabel)}`;
  if (spec.projectType === "update" && spec.groundedOnExistingCodebase) {
    metaLine += `    \\b Grounded On:\\b0  ${escapeRtf(spec.groundedOnExistingCodebase)}`;
  }
  lines.push(`${metaLine}\\par`);
  lines.push("\\page");

  // --- Sections ---
  for (const section of spec.sections) {
    lines.push(`\\fs36\\b\\cf${RTF_CF.navy} ${escapeRtf(section.heading)}\\b0\\par`);
    lines.push(`\\brdrb\\brdrs\\brdrw15\\brdrcf${RTF_CF.blue}\\par\\pard\\par`);
    const caption = `Drafted by ${section.authorAgentName}${section.reviewedByAgentName ? ` · Reviewed by ${section.reviewedByAgentName}` : ""}`;
    lines.push(`\\fs16\\i\\cf${RTF_CF.muted} ${escapeRtf(caption)}\\i0\\par\\par`);

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "table") {
        lines.push(buildRtfTable(block.rows));
        continue;
      }
      const plain = escapeRtf(stripBoldMarkers(block.text));
      if (block.type === "h2") {
        lines.push(`\\fs28\\b\\cf${RTF_CF.blue} ${plain}\\b0\\par`);
      } else if (block.type === "h3") {
        lines.push(`\\fs24\\b\\cf${RTF_CF.gray} ${plain}\\b0\\par`);
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) lines.push(`\\f1\\fs18\\cf${RTF_CF.gray} ${escapeRtf(codeLine || " ")}\\f0\\par`);
      } else if (block.type === "bullet" || block.type === "numbered") {
        // A literal bullet glyph + tab, not a true applied RTF list — renders visually
        // fine in Word/LibreOffice/TextEdit but isn't a "real" list a reader could
        // re-number or restyle. Acceptable tradeoff for a dependency-free RTF writer.
        lines.push(`\\fs22\\cf${RTF_CF.gray} \\bullet \\tab ${plain}\\par`);
      } else {
        lines.push(`\\fs22\\cf${RTF_CF.gray} ${plain}\\par`);
      }
    }
    lines.push("\\par");
  }

  // --- Closing block ---
  lines.push(`\\brdrb\\brdrs\\brdrw10\\brdrcf${RTF_CF.ruleLight}\\par\\pard\\par`);
  lines.push(`\\qc\\fs20\\i\\cf${RTF_CF.muted} ${escapeRtf("— End of Document —")}\\i0\\par`);
  lines.push(`\\qc\\fs18\\cf${RTF_CF.faint} ${escapeRtf(spec.title)} Product Specification  |  ${escapeRtf(dateLabel)}  |  AI-Generated Draft\\par`);
  lines.push("}");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// PDF (pdf-lib direct construction — see src/lib/pdfExport.ts for the sibling
// implementation this borrows its wrapping/pagination approach from)
// ---------------------------------------------------------------------------

const PAGE_WIDTH = 612; // US Letter, points
const PAGE_HEIGHT = 792;
const MARGIN = 54; // 0.75in, matching the reference document and the DOCX renderer above
const HEADER_H = 34;
const FOOTER_H = 28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const CONTENT_TOP = PAGE_HEIGHT - MARGIN - HEADER_H;
const CONTENT_BOTTOM = MARGIN + FOOTER_H;

export function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, fontSize) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function buildProductSpecPdf(spec: ProductSpec): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const regularFont = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const italicFont = await doc.embedFont(StandardFonts.HelveticaOblique);
  const monoFont = await doc.embedFont(StandardFonts.Courier);

  const [navy, blue, gray, muted, faint, accent, tableBorder, ruleLight, labelFill] = [
    BRAND.navy, BRAND.blue, BRAND.gray, BRAND.muted, BRAND.faint, BRAND.accent, BRAND.tableBorder, BRAND.ruleLight, BRAND.labelFill,
  ].map(hexToRgb01);
  const c = (rgbTuple: [number, number, number]) => rgb(...rgbTuple);

  const dateLabel = specDateLabel(spec);
  const allPages: PDFPage[] = [];

  // Header/footer text is static (module-level info, not flowing content), so it's drawn
  // once per page as each page is created, except the footer's page NUMBER — that's drawn
  // in one final pass over allPages once the true page count is known, rather than trying
  // to predict it up front.
  const drawHeaderChrome = (p: PDFPage) => {
    const y = PAGE_HEIGHT - MARGIN;
    p.drawText(`${spec.title} — Product Specification`, { x: MARGIN, y: y - 9, size: 9, font: boldFont, color: c(blue) });
    const rightText = "AI-GENERATED — DRAFT";
    const rightWidth = regularFont.widthOfTextAtSize(rightText, 8);
    p.drawText(rightText, { x: PAGE_WIDTH - MARGIN - rightWidth, y: y - 8, size: 8, font: regularFont, color: c(muted) });
    p.drawLine({ start: { x: MARGIN, y: y - 16 }, end: { x: PAGE_WIDTH - MARGIN, y: y - 16 }, thickness: 0.75, color: c(blue) });
  };

  let page: PDFPage = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  allPages.push(page);
  drawHeaderChrome(page);
  let cursorY = CONTENT_TOP;

  const ensureSpace = (neededHeight: number) => {
    if (cursorY - neededHeight < CONTENT_BOTTOM) {
      page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      allPages.push(page);
      drawHeaderChrome(page);
      cursorY = CONTENT_TOP;
    }
  };

  const drawParagraph = (text: string, font: PDFFont, fontSize: number, opts: { color?: [number, number, number]; indent?: number; lineHeight?: number; align?: "left" | "center" } = {}) => {
    const indent = opts.indent || 0;
    const lineHeight = opts.lineHeight || fontSize * 1.4;
    const color = c(opts.color || gray);
    const lines = wrapText(text, font, fontSize, CONTENT_WIDTH - indent);
    for (const line of lines) {
      ensureSpace(lineHeight);
      const x = opts.align === "center" ? MARGIN + (CONTENT_WIDTH - font.widthOfTextAtSize(line, fontSize)) / 2 : MARGIN + indent;
      page.drawText(line, { x, y: cursorY - fontSize, size: fontSize, font, color });
      cursorY -= lineHeight;
    }
  };

  const drawRule = (color: [number, number, number], thickness: number, gapBefore = 8, gapAfter = 8) => {
    cursorY -= gapBefore;
    ensureSpace(thickness);
    page.drawLine({ start: { x: MARGIN, y: cursorY }, end: { x: PAGE_WIDTH - MARGIN, y: cursorY }, thickness, color: c(color) });
    cursorY -= gapAfter;
  };

  // Renders one table: computes wrapped lines per cell up front so each row's height is
  // known before anything is drawn (fills, borders, and text all need that height).
  const drawTable = (rows: string[][]) => {
    const [headerRow, ...bodyRows] = rows;
    const colCount = headerRow.length;
    const colWidth = CONTENT_WIDTH / colCount;
    const cellPad = 5;
    const fontSize = 9;
    const lineHeight = fontSize * 1.3;

    const drawRowLine = (cells: string[], isHeader: boolean) => {
      const wrapped = cells.map(cell => wrapText(stripBoldMarkers(cell), isHeader ? boldFont : regularFont, fontSize, colWidth - cellPad * 2));
      const rowHeight = Math.max(...wrapped.map(w => w.length), 1) * lineHeight + cellPad * 2;
      ensureSpace(rowHeight);
      const rowTop = cursorY;
      for (let ci = 0; ci < colCount; ci++) {
        const cellX = MARGIN + ci * colWidth;
        if (isHeader) {
          page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, color: c(navy) });
        } else if (ci === 0) {
          page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, color: c(labelFill) });
        }
        page.drawRectangle({ x: cellX, y: rowTop - rowHeight, width: colWidth, height: rowHeight, borderColor: c(tableBorder), borderWidth: 0.5, opacity: 0 });
        const textColor = isHeader ? rgb(1, 1, 1) : ci === 0 ? c(navy) : c(gray);
        wrapped[ci].forEach((line, li) => {
          page.drawText(line, { x: cellX + cellPad, y: rowTop - cellPad - fontSize - li * lineHeight, size: fontSize, font: isHeader || ci === 0 ? boldFont : regularFont, color: textColor });
        });
      }
      cursorY = rowTop - rowHeight;
    };

    drawRowLine(headerRow, true);
    for (const row of bodyRows) drawRowLine(row, false);
    cursorY -= 10;
  };

  // --- Title page ---
  const titlePageStartCount = allPages.length;
  cursorY -= 20;
  drawParagraph("PRODUCT SPECIFICATION", boldFont, 10, { color: blue });
  cursorY -= 6;
  drawParagraph(spec.title, boldFont, 30, { color: navy });
  if (spec.subtitle) drawParagraph(spec.subtitle, regularFont, 15, { color: blue });
  drawRule(accent, 1.5, 10, 16);
  drawParagraph("Document Purpose", boldFont, 12, { color: navy });
  cursorY -= 2;
  drawParagraph(
    `This document is a comprehensive, implementation-ready product specification for ${spec.title}, produced collaboratively by a multi-agent AI product team. ${spec.appConcept || ""}`,
    regularFont,
    10.5,
    { color: gray }
  );
  if (spec.groundedSources && spec.groundedSources.length > 0) {
    cursorY -= 14;
    drawParagraph("Knowledge Sources Referenced", boldFont, 11, { color: navy });
    cursorY -= 2;
    for (const src of spec.groundedSources.slice(0, MAX_GROUNDED_SOURCES_SHOWN)) {
      const sourceLine = `${sourceTypeLabel(src.sourceType)}: ${src.name}${src.url ? `  —  ${src.url}` : ""}`;
      drawParagraph(sourceLine, boldFont, 9.5, { color: gray });
      drawParagraph(src.excerpt, italicFont, 8.5, { color: muted });
      cursorY -= 4;
    }
    if (spec.groundedSources.length > MAX_GROUNDED_SOURCES_SHOWN) {
      drawParagraph(`...and ${spec.groundedSources.length - MAX_GROUNDED_SOURCES_SHOWN} more source(s) not shown here.`, italicFont, 8.5, { color: muted });
    }
  }
  cursorY -= 16;
  const toolLabel = specToolLabel(spec);
  const typeLabel = specTypeLabel(spec);
  let metaText = `Generated:  ${dateLabel}     Target Tool:  ${toolLabel}     Type:  ${typeLabel}`;
  if (spec.projectType === "update" && spec.groundedOnExistingCodebase) metaText += `     Grounded On:  ${spec.groundedOnExistingCodebase}`;
  drawParagraph(metaText, regularFont, 9.5, { color: gray });

  // Force the rest of the content onto its own page, matching the reference document —
  // but only if the title page content (which can now run long with several knowledge
  // sources listed) hasn't already spilled onto a new page by itself, which would
  // otherwise leave a wasted blank page between the title page and section 1.
  if (allPages.length === titlePageStartCount) {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    allPages.push(page);
    drawHeaderChrome(page);
  }
  cursorY = CONTENT_TOP;

  // --- Sections ---
  for (const section of spec.sections) {
    ensureSpace(50);
    drawParagraph(section.heading, boldFont, 16, { color: navy });
    drawRule(blue, 1.2, 4, 10);
    const caption = `Drafted by ${section.authorAgentName}${section.reviewedByAgentName ? ` · Reviewed by ${section.reviewedByAgentName}` : ""}`;
    drawParagraph(caption, italicFont, 8, { color: muted });
    cursorY -= 6;

    for (const block of parseMarkdownLiteBlocks(section.content)) {
      if (block.type === "table") {
        drawTable(block.rows);
        cursorY -= 4;
        continue;
      }
      const plain = stripBoldMarkers(block.text);
      if (block.type === "h2") {
        cursorY -= 4;
        drawParagraph(plain, boldFont, 12.5, { color: blue });
      } else if (block.type === "h3") {
        drawParagraph(plain, boldFont, 11, { color: gray });
      } else if (block.type === "code") {
        for (const codeLine of block.text.split("\n")) drawParagraph(codeLine || " ", monoFont, 8.5, { color: gray, indent: 12, lineHeight: 11 });
      } else if (block.type === "bullet" || block.type === "numbered") {
        drawParagraph(`•  ${plain}`, regularFont, 10, { indent: 10 });
      } else {
        drawParagraph(plain, regularFont, 10);
      }
      cursorY -= 4;
    }
    cursorY -= 10;
  }

  // --- Closing block ---
  drawRule(ruleLight, 0.75, 8, 16);
  drawParagraph("— End of Document —", italicFont, 10, { color: muted, align: "center" });
  drawParagraph(`${spec.title} Product Specification  |  ${dateLabel}  |  AI-Generated Draft`, regularFont, 9, { color: faint, align: "center" });

  // --- Footer, drawn last across every page now that the true page count is known ---
  allPages.forEach((p, idx) => {
    const y = MARGIN + FOOTER_H - 14;
    p.drawLine({ start: { x: MARGIN, y: y + 10 }, end: { x: PAGE_WIDTH - MARGIN, y: y + 10 }, thickness: 0.5, color: c(ruleLight) });
    p.drawText(`Generated by Orchestra — ${dateLabel}`, { x: MARGIN, y, size: 8, font: regularFont, color: c(muted) });
    const pageText = `Page ${idx + 1}`;
    const pageTextWidth = regularFont.widthOfTextAtSize(pageText, 8);
    p.drawText(pageText, { x: PAGE_WIDTH - MARGIN - pageTextWidth, y, size: 8, font: regularFont, color: c(muted) });
  });

  return doc.save();
}

// ---------------------------------------------------------------------------
// Download helper (binary-safe — src/lib/productSpecGenerator.ts's downloadFile is
// string-only and would corrupt a .docx/.pdf's binary content).
// ---------------------------------------------------------------------------

export function downloadBinaryFile(filename: string, data: Blob | Uint8Array, mimeType: string): void {
  const blob = data instanceof Blob ? data : new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
