// Zero-dependency exports of a collaborative run: a Markdown decision record in
// MADR-adjacent format (lands cleanly in Git repos, Confluence, and Notion), and a
// versioned JSON schema (turns Orchestra from a document dead-end into a data source —
// BI ingestion, webhook automation, programmatic diffing of re-runs).
// Structural input type is deliberately narrow so this module stays testable without
// importing the app's full run type.

import type { DecisionNode } from "./treeUtils";
import { getTreeChildren } from "./treeUtils";

export interface RunExportInput {
  prompt: string;
  outcome: string;
  reasons: string[];
  decisionTree: DecisionNode[];
  facilitatorAgentName?: string;
  dissent?: { agentName: string; position: string; wouldChangeIf: string }[];
  axes?: { id: string; label: string; priority: number; independent: boolean; description?: string }[];
  considerations?: {
    text: string;
    category: string;
    flaggedForReview: boolean;
    managerResponse?: { stance: string; chosenAlternative?: string; note?: string };
  }[];
  rounds: number;
  premiseAmendments?: string;
  groundedSourceCount?: number;
  hadVerifiedCalculations?: boolean;
  timestamp?: string;
  spawnedRunIds?: string[];
  revisitEvents?: { timestamp: string; trigger: string; note: string; newRunId: string }[];
}

export const RUN_EXPORT_SCHEMA_VERSION = 1;

function treeToMarkdown(nodes: DecisionNode[], parentId: string | null = null, depth = 0): string {
  return getTreeChildren(nodes, parentId)
    .map(n => {
      const marker = n.isSelected ? "**" : "";
      const line = `${"  ".repeat(depth)}- ${marker}${n.label} (${n.probability}%)${marker}${n.mandateNote ? " _[mandated]_" : ""}${n.reason ? ` — ${n.reason}` : ""}`;
      const children = treeToMarkdown(nodes, n.id, depth + 1);
      return children ? `${line}\n${children}` : line;
    })
    .join("\n");
}

/** MADR-adjacent decision record: Status / Context / Decision / Options / Consequences /
 *  Dissent — the anatomy engineering organisations already standardise on for ADRs. */
export function buildMarkdownDecisionRecord(run: RunExportInput): string {
  const date = (run.timestamp || new Date().toISOString()).slice(0, 10);
  const parts: string[] = [];

  parts.push(`# Decision Record: ${run.prompt.length > 80 ? `${run.prompt.slice(0, 80)}…` : run.prompt}`);
  parts.push("");
  parts.push(`- **Status:** ${run.dissent && run.dissent.length > 0 ? "accepted (with recorded dissent)" : "accepted"}`);
  parts.push(`- **Date:** ${date}`);
  if (run.facilitatorAgentName) parts.push(`- **Facilitator:** ${run.facilitatorAgentName}`);
  parts.push(`- **Discussion rounds:** ${run.rounds}`);
  parts.push("");

  parts.push("## Context");
  parts.push("");
  parts.push(run.prompt);
  if (run.premiseAmendments) {
    parts.push("");
    parts.push("### Amended premises");
    parts.push("");
    parts.push(run.premiseAmendments);
  }
  parts.push("");

  parts.push("## Decision");
  parts.push("");
  parts.push(run.outcome);
  parts.push("");

  if (run.reasons.length > 0) {
    parts.push("## Rationale");
    parts.push("");
    for (const r of run.reasons) parts.push(`- ${r}`);
    parts.push("");
  }

  if (run.decisionTree.length > 0) {
    parts.push("## Options considered");
    parts.push("");
    parts.push("Selected paths in **bold**; probabilities as assessed by the panel.");
    parts.push("");
    parts.push(treeToMarkdown(run.decisionTree));
    parts.push("");
  }

  if (run.considerations && run.considerations.length > 0) {
    parts.push("## Considerations and responses");
    parts.push("");
    parts.push("| Consideration | Category | Manager response |");
    parts.push("|---|---|---|");
    for (const c of run.considerations) {
      const resp = !c.managerResponse || c.managerResponse.stance === "agree"
        ? "agreed"
        : c.managerResponse.stance === "alternative"
          ? `alternative: ${c.managerResponse.chosenAlternative || ""}`
          : c.managerResponse.note || c.managerResponse.stance;
      const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
      parts.push(`| ${esc(c.text)} | ${c.category} | ${esc(resp)} |`);
    }
    parts.push("");
  }

  if (run.dissent && run.dissent.length > 0) {
    parts.push("## Dissenting opinions");
    parts.push("");
    for (const d of run.dissent) {
      parts.push(`- **${d.agentName}:** ${d.position}${d.wouldChangeIf ? ` _(revisit if: ${d.wouldChangeIf})_` : ""}`);
    }
    parts.push("");
  }

  parts.push("---");
  parts.push(`_Generated by Orchestra on ${date}._`);
  parts.push("");
  return parts.join("\n");
}

/** Versioned machine-readable export. Includes the tree as a flat adjacency list —
 *  pivot- and query-friendly — rather than a nested structure. */
export function buildRunJson(run: RunExportInput): string {
  return JSON.stringify(
    {
      schemaVersion: RUN_EXPORT_SCHEMA_VERSION,
      generatedAt: new Date().toISOString(),
      prompt: run.prompt,
      outcome: run.outcome,
      reasons: run.reasons,
      facilitator: run.facilitatorAgentName || null,
      rounds: run.rounds,
      premiseAmendments: run.premiseAmendments || null,
      decisionTree: run.decisionTree.map(n => ({
        id: n.id,
        parentId: n.parentId,
        label: n.label,
        probability: n.probability,
        selected: n.isSelected === true,
        reason: n.reason || null,
        mandateNote: n.mandateNote || null
      })),
      axes: (run.axes || []).map(a => ({
        id: a.id, label: a.label, priority: a.priority, independent: a.independent, description: a.description || null
      })),
      considerations: (run.considerations || []).map(c => ({
        text: c.text,
        category: c.category,
        flaggedForReview: c.flaggedForReview,
        managerResponse: c.managerResponse || null
      })),
      dissent: run.dissent || []
    },
    null,
    2
  );
}

export function downloadTextFile(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/** A structured, plain-language audit trail — deliberately NOT another ADR. The Markdown
 *  decision record above is written for developers who already think in Status/Context/
 *  Decision headers; this is written for a compliance officer, auditor, or board member
 *  who needs to understand what was decided, what was and wasn't verified, and how any
 *  disagreement was handled, without needing to know what an ADR is. Zero-LLM, deterministic
 *  — built entirely from data the run already has. */
export interface AuditSection {
  heading: string;
  paragraphs: string[];
}

export function buildHumanReadableAudit(run: RunExportInput): AuditSection[] {
  const sections: AuditSection[] = [];
  const date = (run.timestamp || new Date().toISOString()).slice(0, 10);

  sections.push({
    heading: "What was being decided",
    paragraphs: [run.prompt, `This record was produced on ${date}${run.facilitatorAgentName ? `, facilitated by ${run.facilitatorAgentName}` : ""}, after ${run.rounds} round${run.rounds === 1 ? "" : "s"} of discussion.`]
  });

  sections.push({
    heading: "What was decided",
    paragraphs: [run.outcome]
  });

  if (run.reasons.length > 0) {
    sections.push({
      heading: "Why this was decided",
      paragraphs: run.reasons
    });
  }

  // Grounding status stated in plain terms — the same fact the live verification-status
  // line and shared-view badge show, phrased for a reader who wasn't in the app.
  const groundingParagraph = run.groundedSourceCount && run.groundedSourceCount > 0
    ? `Figures and claims in this discussion were checked against ${run.groundedSourceCount} uploaded source document${run.groundedSourceCount === 1 ? "" : "s"}${run.hadVerifiedCalculations ? ", and at least one figure was confirmed with an exact calculation rather than estimated" : ""}. Any figure not traceable to those sources was flagged in the live discussion for the manager to verify.`
    : "No source documents were uploaded for this discussion, so figures and claims were not checked against any external material. Treat quantitative claims as estimates unless independently verified.";
  sections.push({ heading: "What was checked", paragraphs: [groundingParagraph] });

  if (run.dissent && run.dissent.length > 0) {
    const dissentParagraphs = run.dissent.map(d =>
      `${d.agentName} disagreed with the outcome above: "${d.position}" They indicated they would reconsider if: ${d.wouldChangeIf}`
    );
    sections.push({ heading: "Disagreement recorded during the discussion", paragraphs: dissentParagraphs });
  }

  // Revisit history in plain language — previously invisible from the original run's own
  // perspective; this is where that provenance actually gets read by a human.
  if (run.revisitEvents && run.revisitEvents.length > 0) {
    const revisitParagraphs = run.revisitEvents.map(e => {
      const when = new Date(e.timestamp).toLocaleDateString();
      const reason = e.trigger === "go_deeper" ? "the manager asked the team to go deeper"
        : e.trigger === "dissent_revisit" ? "a recorded disagreement's condition was reported as having occurred"
        : e.trigger === "discuss_batch" ? "the manager raised feedback on specific parts of the decision"
        : "the manager requested a re-discussion";
      return `On ${when}, this decision was revisited because ${reason}. That produced a separate, later record (reference: ${e.newRunId}).`;
    });
    sections.push({ heading: "Later revisions to this decision", paragraphs: revisitParagraphs });
  }

  if (run.considerations && run.considerations.length > 0) {
    const considerationParagraphs = run.considerations.map(c => {
      const stance = c.managerResponse?.stance === "override" ? " The manager overrode this." : c.managerResponse?.note ? ` Manager's note: ${c.managerResponse.note}` : "";
      return `[${c.category}] ${c.text}${stance}`;
    });
    sections.push({ heading: "Assumptions, risks, and constraints considered", paragraphs: considerationParagraphs });
  }

  if (run.spawnedRunIds && run.spawnedRunIds.length > 0) {
    sections.push({
      heading: "Related records",
      paragraphs: [`This decision led to ${run.spawnedRunIds.length} follow-up discussion${run.spawnedRunIds.length === 1 ? "" : "s"}. Ask the person who ran this session for the corresponding record(s) if you need the fuller history.`]
    });
  }

  return sections;
}

/** Plain-text rendering of the audit sections, for the instant Markdown-adjacent export
 *  (no bold/heading syntax — meant to read naturally even pasted into an email or a plain
 *  document, not just a Markdown renderer). */
export function auditSectionsToPlainText(sections: AuditSection[], title: string): string {
  const lines = [title, "=".repeat(title.length), ""];
  for (const section of sections) {
    lines.push(section.heading.toUpperCase());
    lines.push("-".repeat(section.heading.length));
    for (const p of section.paragraphs) lines.push(p, "");
  }
  return lines.join("\n").trim() + "\n";
}

